In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
#Import
import numpy as np
import pandas as pd
import warnings
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

warnings.simplefilter("ignore")


In [4]:
df1 = pd.read_csv('/content/drive/MyDrive/Data Science - Equipo: Zelada, Caceres M., Rodriguez S./Segunda Pre-Entrega/combats.csv')
df2 = pd.read_csv('/content/drive/MyDrive/Crehana/Data Science/Machine Learning/Random Forest/Copia de pokemon_csv.csv')

In [5]:
df_2 = df2.copy(deep=True)
df_2.drop('nombre', inplace = True, axis = 1)
df_2.drop(['tipo1','tipo2'], inplace = True, axis = 1)
df_2.drop(['Unnamed: 0', 'Unnamed: 0.5', 'Unnamed: 0.4', 'Unnamed: 0.3',	'Unnamed: 0.2', 'Unnamed: 0.1'], inplace=True, axis = 1)
df_2.head()

pokedex_id  altura_m  peso_kg  hp  ataque  defensa  ataque_esp  defensa_esp  \
0          1       0.7      6.9  45      49       49          65           65   
1          2       1.0     13.0  60      62       63          80           80   
2          3       2.0    100.0  80      82       83         100          100   
3          4       0.6      8.5  39      52       43          60           50   
4          5       1.1     19.0  58      64       58          80           65   

   velocidad    generacion  legendario  genero  
0         45  generation-i       False       1  
1         60  generation-i       False       1  
2         80  generation-i       False       1  
3         65  generation-i       False       1  
4         80  generation-i       False       1

In [6]:
difaltura_m = []
difpeso_kg = []
difhp = []
difataque = []
difdefensa = []
difataque_esp = []
difdefensa_esp = []
difvelocidad = []

for i in range(len(df1.Winner)):

  difaltura_m.append(df_2.altura_m[df1.First_pokemon[i]] - df_2.altura_m[df1.Second_pokemon[i]])

  difpeso_kg.append(df_2.peso_kg[df1.First_pokemon[i]] - df_2.peso_kg[df1.Second_pokemon[i]])

  difhp.append(df_2.hp[df1.First_pokemon[i]] - df_2.hp[df1.Second_pokemon[i]])

  difataque.append(df_2.ataque[df1.First_pokemon[i]] - df_2.ataque[df1.Second_pokemon[i]])

  difdefensa.append(df_2.defensa[df1.First_pokemon[i]] - df_2.defensa[df1.Second_pokemon[i]])

  difataque_esp.append(df_2.ataque_esp[df1.First_pokemon[i]] - df_2.ataque_esp[df1.Second_pokemon[i]])

  difdefensa_esp.append(df_2.defensa_esp[df1.First_pokemon[i]] - df_2.defensa_esp[df1.Second_pokemon[i]])

  difvelocidad.append(df_2.velocidad[df1.First_pokemon[i]] - df_2.velocidad[df1.Second_pokemon[i]])


df1['difaltura_m'] = difaltura_m
df1['difpeso_kg'] = difpeso_kg
df1['difhp'] = difhp
df1['difataque'] = difataque
df1['difdefensa'] = difdefensa
df1['difataque_esp'] = difataque_esp
df1['difdefensa_esp'] = difdefensa_esp
df1['difvelocidad'] = difvelocidad


binwin = []

for i in range(len(df1.Winner)):
  if df1.Winner[i] == df1.First_pokemon[i]:
    binwin.append(0)
  elif df1.Winner[i] == df1.Second_pokemon[i]:
    binwin.append(1)
  else:
    binwin.append(np.nan)

df1['binwin'] = binwin

df1.head()

First_pokemon  Second_pokemon  Winner  difaltura_m  difpeso_kg  difhp  \
0            266             298     298          0.0       -68.6     30   
1            702             701     701          0.1         3.5    -17   
2            191             668     668          0.7         8.4     31   
3            237             683     683          0.0         2.5    -17   
4            151             231     151         -0.2      -113.6    -45   

   difataque  difdefensa  difataque_esp  difdefensa_esp  difvelocidad  binwin  
0         25         -85             55             -40            35       1  
1         -8          93            -31              83           -51       1  
2         37          16             44               6           -12       1  
3        -18         -51             26               8            16       1  
4        -71         -55            -11               5            -5       0

In [7]:
df1.binwin.value_counts()

1    26399
0    23601
Name: binwin, dtype: int64

In [8]:
columns1 = df1.columns.tolist()[:]
columns1


['First_pokemon',
 'Second_pokemon',
 'Winner',
 'difaltura_m',
 'difpeso_kg',
 'difhp',
 'difataque',
 'difdefensa',
 'difataque_esp',
 'difdefensa_esp',
 'difvelocidad',
 'binwin']

In [9]:
df1.head()

First_pokemon  Second_pokemon  Winner  difaltura_m  difpeso_kg  difhp  \
0            266             298     298          0.0       -68.6     30   
1            702             701     701          0.1         3.5    -17   
2            191             668     668          0.7         8.4     31   
3            237             683     683          0.0         2.5    -17   
4            151             231     151         -0.2      -113.6    -45   

   difataque  difdefensa  difataque_esp  difdefensa_esp  difvelocidad  binwin  
0         25         -85             55             -40            35       1  
1         -8          93            -31              83           -51       1  
2         37          16             44               6           -12       1  
3        -18         -51             26               8            16       1  
4        -71         -55            -11               5            -5       0

## Train-Test Split

In [10]:
y = df1.binwin
combat_features = ['First_pokemon', 'Second_pokemon', 'difhp', 'difataque', 'difdefensa', 'difataque_esp', 'difdefensa_esp', 'difvelocidad']
X = df1[combat_features]

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=33,
                                                    stratify= y)


print('Tamaño del set de entrenamiento:', X_train.shape)
print('Tamaño del set de testeo:', X_test.shape)


Tamaño del set de entrenamiento: (40000, 8)
Tamaño del set de testeo: (10000, 8)


## Random Forest Classifier

In [11]:
forest_model_cl = RandomForestClassifier(random_state=1)
forest_model_cl.fit(X_train, y_train)

RandomForestClassifier(random_state=1)

In [12]:
y_pred = forest_model_cl.predict(X_test)

In [13]:
print(y_pred)

[0 1 1 ... 1 0 1]


In [14]:
print('Matriz de confusion:')
print(metrics.confusion_matrix(y_test, y_pred))
print('Classification report:')
print(metrics.classification_report(y_test,y_pred))
print('-----------------------------------------------------------------------------')
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print('Precision:',metrics.precision_score(y_test, y_pred))
print('Recall:',metrics.recall_score(y_test, y_pred))
print('F1:',metrics.f1_score(y_test, y_pred))

Matriz de confusion:
[[3004 1716]
 [1313 3967]]
Classification report:
              precision    recall  f1-score   support

           0       0.70      0.64      0.66      4720
           1       0.70      0.75      0.72      5280

    accuracy                           0.70     10000
   macro avg       0.70      0.69      0.69     10000
weighted avg       0.70      0.70      0.70     10000

-----------------------------------------------------------------------------
Accuracy: 0.6971
Precision: 0.698046806264297
Recall: 0.7513257575757576
F1: 0.7237070145033295


## Random Forest Regressor

Para un problema de clasificación?

In [15]:
forest_model_reg = RandomForestRegressor(random_state=1)
forest_model_reg.fit(X_train, y_train)

RandomForestRegressor(random_state=1)

In [16]:
predictions = forest_model_reg.predict(X_test)

In [17]:
print(predictions)

[0.12 0.23 0.5  ... 0.85 0.65 0.8 ]


In [18]:
predictionsint = []

for i in range(len(predictions)):
  if int(predictions[i]) - X_test.First_pokemon[X_test.index[i]] > int(predictions[i]) - X_test.Second_pokemon[X_test.index[i]]:
    predictionsint.append(X_test.First_pokemon[X_test.index[i]])
  else:
    predictionsint.append(X_test.Second_pokemon[X_test.index[i]])

print(predictionsint)

[164, 566, 174, 116, 210, 100, 36, 259, 283, 300, 370, 363, 483, 458, 34, 55, 281, 451, 212, 73, 128, 37, 37, 110, 151, 426, 373, 301, 312, 1, 328, 129, 187, 701, 71, 229, 272, 276, 292, 182, 454, 704, 162, 727, 206, 274, 175, 601, 61, 69, 293, 49, 391, 64, 215, 134, 113, 232, 14, 206, 383, 11, 281, 393, 127, 403, 477, 47, 206, 39, 226, 65, 139, 128, 177, 291, 656, 210, 469, 403, 89, 596, 31, 586, 255, 68, 344, 221, 119, 473, 270, 690, 763, 39, 95, 571, 38, 103, 439, 29, 112, 399, 140, 410, 672, 123, 483, 543, 345, 435, 391, 17, 38, 202, 420, 636, 166, 563, 288, 465, 18, 467, 222, 635, 560, 24, 31, 224, 552, 225, 19, 11, 76, 317, 107, 460, 267, 154, 314, 122, 56, 334, 73, 110, 323, 124, 329, 92, 107, 109, 11, 386, 248, 573, 248, 79, 504, 293, 627, 551, 454, 468, 555, 467, 435, 466, 40, 240, 482, 26, 296, 318, 25, 545, 25, 123, 205, 362, 79, 299, 558, 724, 268, 124, 477, 375, 356, 189, 288, 55, 565, 495, 171, 356, 720, 700, 167, 125, 233, 277, 134, 661, 576, 356, 161, 36, 113, 95, 11, 5

In [19]:
results = X_test.copy(deep=True)
results.drop(['difhp', 'difataque', 'difdefensa', 'difataque_esp', 'difdefensa_esp',
 'difvelocidad'], inplace = True, axis = 1)
results['prediction'] = predictionsint
results.sample(10)

First_pokemon  Second_pokemon  prediction
19875            163             359         163
14840            409             583         409
11103            718             187         187
44873            733             716         716
7225             468             391         391
49120            388             294         294
30318            668              11          11
26980            130             565         130
13670            400              95          95
42249            197             156         156

Dado que la predicción generada no es binaria, sino discreta, deberemos transformarlas. Para ello estableceremos un limite:

En este caso puntual utilizaremos 0.5 como limite. 
En el rango 0.5 - 1 consideraremos la respuesta como 1/True
en el rango 0 - 0.49 consideraremos la predicción como 0/False

**Sugerencia:** Probar con diferentes rangos y comparar resultados

In [20]:
y_pred = []

for i in predictions:
  if i >= 0.5:
    y_pred.append(1)
  else:
    y_pred.append(0)

print(np.array(y_pred))

[0 0 1 ... 1 1 1]


In [21]:
print('Matriz de confusion:')
print(metrics.confusion_matrix(y_test, y_pred))
print('Classification report:')
print(metrics.classification_report(y_test,y_pred))
print('-----------------------------------------------------------------------------')
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print('Precision:',metrics.precision_score(y_test, y_pred))
print('Recall:',metrics.recall_score(y_test, y_pred))
print('F1:',metrics.f1_score(y_test, y_pred))

Matriz de confusion:
[[3173 1547]
 [1353 3927]]
Classification report:
              precision    recall  f1-score   support

           0       0.70      0.67      0.69      4720
           1       0.72      0.74      0.73      5280

    accuracy                           0.71     10000
   macro avg       0.71      0.71      0.71     10000
weighted avg       0.71      0.71      0.71     10000

-----------------------------------------------------------------------------
Accuracy: 0.71
Precision: 0.717391304347826
Recall: 0.74375
F1: 0.7303328993862749
